modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="urbanforma"
version="1.05"
displayName="UrbanForma"
description='''这是一个添加更多装饰性方块的模组This is a mod that adds more decorative blocks.'''
authors="Dotkk"
logoFile="1_Urban Formalogo.png"

[[dependencies]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"