modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="urbanforma"
version="1.05b"
displayName="UrbanForma"
description='''A modern urban construction mod'''
authors="Dotkk"

[[dependencies]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"